name: 'Auto Assign'
on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto Assign Action'
        uses: kentaro-m/auto-assign-action@v1.2.3
        with:
          addReviewers: true
          addAssignees: false
          reviewers:
            - cw123
            - ilixiaocui
            - wuhongsong
            - Cyber-SiKu
            - jolly-sy
          numberOfReviewers: 1
